version: '3.7'

services:
  service_01:
    image: service-01:latest
    restart: unless-stopped
    build:
      context: services/user_service
      dockerfile: Dockerfile
    networks:
      - test
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq

  service_02:
    image: service-02:latest
    restart: unless-stopped
    build:
      context: services/order_service
      dockerfile: Dockerfile
    networks:
      - test
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: bitnami/rabbitmq:latest
    networks:
      - test

networks:
  test: