version: '3.7'

services:
  service_01:
    image: service-01:latest
    restart: unless-stopped
    build:
      context: services/user_service
      dockerfile: Dockerfile
    networks:
      - test
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq

  service_02:
    image: service-02:latest
    restart: unless-stopped
    build:
      context: services/order_service
      dockerfile: Dockerfile
    networks:
      - test
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_VIRTUALHOST=/
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD='guest'
      - RABBITMQ_PREFETCHCOUNT=16
      - RABBITMQ_DURABLE=true
      - RABBITMQ_LAZY=false
    networks:
      - test
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  test: